name: docker-containers
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  setup-node:
    runs-on: ubuntu-latest
    container:
      image: node:16
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.ghcr_token }}
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/tmp
      options: --cpus 0.2 --network-alias maincontainer
    steps:
      - uses: actions/checkout@v2
      - run: npm -v
      - run: node -v
